languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
title = "Amazon CloudOps Networking Workshop"
theme = "learn"
uglyurls = true
sectionPagesMenu = "main"
relativeURLs = true
publishDir= "public/"
[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Marine Haddad"
description = "Amazon CloudOps Networking Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
editURL = "https://github.com/marinehadd/aws-cloudops-networking/edit/master/content/" # Add github URL
baseURL = "https://networking.aws-cloudops.com/index.html"

#

[menu]
  [[menu.main]]
    identifier = "Prerequisites"
    name = "This is the Mu track"
    title = "Workshop using Mu"
    url = "/mu/"
    weight = -110

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin fa-lg'></i> Marine Haddad"
identifier = "li1"
url = "https://www.linkedin.com/in/marine-haddad-38a542b5/"
weight = 1
Email = "marinehd@amazon.com"

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin fa-lg'></i> Adrianna Kurzela"
identifier = "li2"
url = "https://www.linkedin.com/in/adrianna-kurzela-26b88210b/"
weight = 2
Email = "akurzela@amazon.lu"


# Deploy to S3 + CloudFront
[deployment]
  [[deployment.targets]]
    name = "S3"
    URL = "s3://cloudops-s3-website?region=eu-west-1"
    cloudFrontDistributionID = "E2G13Z9GIV62G1"


[markup.goldmark.renderer]
unsafe= true

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
